python ../code/dpo.py \
    --dataset_name ../data/dpo \
    --model_name_or_path Llama3.1-8b-Instruct-May-11-with-context-sft \
    --learning_rate 5.0e-6 \
    --num_train_epochs 2 \
    --per_device_train_batch_size 1 \
    --gradient_accumulation_steps 8 \
    --gradient_checkpointing \
    --logging_steps 25 \
    --eval_strategy steps \
    --eval_steps 50 \
    --output_dir Llama3.1-8b-Instruct-May-11-with-context-dpo \
    --no_remove_unused_columns \
    --use_peft \
    --lora_r 32 \
    --lora_alpha 16